#include<bits/stdc++.h>
using namespace std;
void funct() throw(int,string,char,runtime_error)
{
    int a=10;
        string s="jasaram";
        //throw a;
        //throw s;
        //throw "some exception";
        throw runtime_error("jasaram choudhary");

}
int main()
{
    try
    {
        funct();
    }
    catch(int a)
    {
        cout<<"integer is : "<<a<<endl;
    }
    catch(string  e)
    {
    cout<<e<<endl;
    }
    catch(const char *e)
    {
        cout<<e<<endl;
    }

    catch(runtime_error &e)
    {
        cout<<e.what()<<endl;
    }
    return 0;
}
